//generated by 3rd party tool ... do not move
class ClassA {
   
   void method() {       
   
      callMethodA();
      /*
       * block comment
       */
      callMethodB();
   /* single line comment */
      callMethodC();
   // end of line
   	// comments
      callMethodD();
   }
};
